name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Build wheel
      run: |
        pip install build
        python -m build
    - name: Upload artifact
codex/conduct-comprehensive-audit-for-jarvis-ai-project-5clmg5
      uses: actions/upload-artifact@v4
=======
      uses: actions/upload-artifact@v3
main
      with:
        name: wheel
        path: dist/*.whl
